name: BentoBox-Brix
main: world.bentobox.brix.BrixPladdon
version: 0.0.2-SNAPSHOT-LOCAL
api-version: "1.21"

authors: [tastybento]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: Plot game for Bentobox
